### ISSUE TITLE
Dynamic loading of libRmath.so fails on OS X

### ISSUE THREAD

**Issue by hoelzl** [tpapp/cl-rmath#1]
Loading cl-rmath on OS X (using SBCL 1.0.57.49-d720bc3) fails with the following error message 

```
Unable to load foreign library (LIBRMATH).
  Error opening shared object "libRmath.so":
  dlopen(libRmath.so, 10): image not found.
   [Condition of type CFFI:LOAD-FOREIGN-LIBRARY-ERROR]
```

This happens because `:unix` is in `*features*`, but the dynamic library is called `libRmath.dylib` on OS X.  A simple fix is to change the definition of `librmath` to

```
(cffi:define-foreign-library librmath
  (:darwin "libRmath.dylib")
  (:unix "libRmath.so")
  (t (:default "libRmath")))
```

**Comment by ghost** [comment]
As a quick hack, you can change cl-rmath.i :unix line to:

(:unix "/path/to/libRmath.dylib")

then type 'make' to rebuild cl-rmath.lisp. If you don't have swig, you can get it via brew install swig. 

This presupposes you have libRmath.dylib on your system. If not, I didn't by default though I have R and RStudio installed, you can download R sources from cran and decompress, cd to <decompressed R directory>/src/nmath/standalone, then ./configure and make. Assuming your R was in ~/src/ then your path would be "~/src/<decompressed R directory>/src/nmath/standalone/libRmath.dylib". I wasn't able to find libRmath via brew or macports, so source was the only way and, as I say, it doesn't come by default with the binary R distributions I had. Great stuff Tamas!
